spring:
  application:
    name: techmya
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:mysql://ssg-java2.iptime.org/techdb
    username: tcat
    password: 1111
  mybatis:
    mapper-locations: mappers/**/*.xml