spring:
  application:
    name: techmya
  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://ssg-java2.iptime.org/techdb
    username: tcat
    password: 1111

file:
  upload-dir: ./uploads

mybatis:
  mapper-locations: mappers/**/*.xml
